name: CD Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Placeholder deploy step
        run: echo "Deploy step - extend this with your deployment commands"
